export declare const bottom: string;
export declare const closed: string;
export declare const content: string;
export declare const left: string;
export declare const open: string;
export declare const overlay: string;
export declare const right: string;
export declare const sidebar: string;
export declare const top: string;
